#!/usr/bin/env zsh

if ( ! git diff --cached --quiet --exit-code ) || ( ! git diff --quiet --exit-code ); then
    echo Cannot sync with uncommitted changes
    return 1
fi

remote=origin
main=main

currentBranch=$(git branch --show-current)
parentCommit=$(git show-branch --merge-base | head -n 1)
mainCommit=$(git rev-parse $remote/$main)

git fetch $remote --prune --prune-tags

if [[ $currentBranch == $main ]]; then
    echo Rebasing onto $main
    git rebase $remote/$main
    return 0
fi

git checkout -B $main $remote/$main

if [[ $parentCommit == $mainCommit ]]; then
    echo Rebasing onto $main
    git rebase --onto $main $currentBranch
    return 0
fi

git checkout $currentBranch
