#!/usr/bin/env zsh

if ( ! git diff --cached --quiet --exit-code ) || ( ! git diff --quiet --exit-code ); then
    echo Cannot upload with uncommitted changes
    return 1
fi

remote=origin
currentBranch=$(git branch --show-current)

if ( git branch -r | grep -q $remote/$currentBranch ); then
    git push
else
    git push -u $remote $currentBranch
fi
