#!/usr/bin/env zsh

if ( ! git diff --cached --quiet --exit-code ) || ( ! git diff --quiet --exit-code ); then
    echo Cannot sync with uncommitted changes
    return 1
fi

remote=origin
main=main

currentBranch=$(git branch --show-current)
parentBranch=$(git show-branch | grep \* | grep -v "\[$currentBranch" | head -n 1 | sed -E 's/^.*\[(.*)\].*$/\1/')

git fetch $remote
git checkout -B $main $remote/$main

if [[ $currentBranch == $main ]]; then
    return 0
fi

if ( git branch -r --merged | grep -q $remote/$currentBranch ); then
    echo $currentBranch has been merged; deleting local copy
    git push -d $remote $currentBranch
    git branch -D $currentBranch
    return 0
fi

if [[ $parentBranch == $main ]]; then
    echo Rebasing onto $main
    git rebase --onto $main $currentBranch
else
    git checkout $currentBranch
fi
